#!/bin/sh

bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/nofeeder/macs2/nofeeder_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_overlap_ATAC.bed
bedtools intersect -v -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/nofeeder/macs2/nofeeder_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_nooverlap_ATAC.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/feeder_d13/macs2/feeder_d13_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_overlap_ATAC.bed
bedtools intersect -v -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/feeder_d13/macs2/feeder_d13_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_nooverlap_ATAC.bed
bedtools intersect -v -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/nofeeder_consensus.summits.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers.bed
bedtools intersect -v -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/feeder_d13_consensus.summits.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/feeder_d13/macs2/feeder_d13_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_overlap_ATAC.bed
bedtools intersect -v -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/feeder_d13/macs2/feeder_d13_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_nooverlap_ATAC.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/nofeeder/macs2/nofeeder_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_overlap_ATAC.bed
bedtools intersect -v -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers.bed -b /coh_labs/jochan/PRDM1_ATAC/TOBIAS/nofeeder/macs2/nofeeder_consensus.bed | uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_nooverlap_ATAC.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_overlap_ATAC_PRDM1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_RUNX1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_overlap_ATAC_RUNX1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1RUNX1_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_overlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_nooverlap_ATAC_PRDM1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_RUNX1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_nooverlap_ATAC_RUNX1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1RUNX1_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_without_superenhancers_nooverlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_overlap_ATAC_PRDM1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_RUNX1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_overlap_ATAC_RUNX1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1RUNX1_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_overlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_nooverlap_ATAC_PRDM1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_RUNX1uniq_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_nooverlap_ATAC_RUNX1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/memechip/nofeeder_PRDM1RUNX1_peaks.bed|uniq > /coh_labs/jochan/PRDM1_NK/consensus_peak/nofeeder/consensus_summits_with_superenhancers_nooverlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1RUNX_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_overlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1uniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_overlap_ATAC_PRDM1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_RUNXuniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_overlap_ATAC_RUNX1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1uniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_nooverlap_ATAC_PRDM1uniq.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1RUNX_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_nooverlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_RUNXuniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_without_superenhancers_nooverlap_ATAC_RUNX1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1uniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_overlap_ATAC_PRDM1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1RUNX_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_overlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_overlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_RUNXuniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_overlap_ATAC_RUNX1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1uniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_nooverlap_ATAC_PRDM1only.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_PRDM1RUNX_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_nooverlap_ATAC_PRDM1RUNX.bed
bedtools intersect -wa -a /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_nooverlap_ATAC.bed -b /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/memechip/feeder_d13_RUNXuniq_summits.bed > /coh_labs/jochan/PRDM1_NK/consensus_peak/feeder_d13/consensus_summits_with_superenhancers_nooverlap_ATAC_RUNX1only.bed